// ── Module 10B.1.5: the rules that decided what got seeded ──
//
// The registry seed was generated by a script, but the ACCEPTANCE RULES it
// applied are the reason the seed can be trusted, so they live here as tested
// production code rather than only inside a one-off script.

import { describe, expect, it } from "vitest";
import {
  acceptsAsVerifiedSource,
  effectiveHealth,
  isCareersUrl,
  MIN_CUSTOM_PAGE_EVIDENCE,
} from "./seedRules";
import type { SourceVerification } from "./SourceVerifier";

function verification(overrides: Partial<SourceVerification> = {}): SourceVerification {
  return {
    url: "https://acme.test/careers",
    finalUrl: "https://acme.test/careers",
    health: "HEALTHY",
    httpStatus: 200,
    detectedPlatform: "custom_careers",
    errorReason: null,
    checkedAt: "2026-08-08T00:00:00.000Z",
    postingsSeen: 10,
    ...overrides,
  };
}

describe("isCareersUrl", () => {
  it.each([
    "https://acme.test/careers",
    "https://acme.test/jobs",
    "https://careers.acme.test/",
    "https://acme.test/company/open-positions",
    "https://acme.test/join-us",
    "https://acme.test/en/vacancies",
  ])("accepts %s", (url) => {
    expect(isCareersUrl(url)).toBe(true);
  });

  it.each(["https://acme.test/company/about", "https://acme.test/", "https://acme.test/products"])(
    "rejects %s",
    (url) => {
      expect(isCareersUrl(url)).toBe(false);
    },
  );

  it("does not throw on a malformed URL", () => {
    expect(isCareersUrl("not a url")).toBe(false);
  });
});

describe("acceptsAsVerifiedSource — ATS boards", () => {
  it("accepts a board that returned postings", () => {
    expect(
      acceptsAsVerifiedSource(verification({ detectedPlatform: "greenhouse", postingsSeen: 5 })),
    ).toBe(true);
  });

  it("REJECTS a board that returned zero postings", () => {
    // The load-bearing rule. SmartRecruiters answers 200 with an empty board
    // for any slug at all, so an empty board discovered by guessing is not
    // evidence that the board exists.
    expect(
      acceptsAsVerifiedSource(
        verification({ detectedPlatform: "smartrecruiters", postingsSeen: 0 }),
      ),
    ).toBe(false);
  });

  it("rejects a board with an unknown posting count", () => {
    expect(
      acceptsAsVerifiedSource(verification({ detectedPlatform: "lever", postingsSeen: null })),
    ).toBe(false);
  });
});

describe("acceptsAsVerifiedSource — custom careers pages", () => {
  it("accepts a page with enough visible postings on a careers URL", () => {
    expect(
      acceptsAsVerifiedSource(
        verification({
          postingsSeen: MIN_CUSTOM_PAGE_EVIDENCE,
          finalUrl: "https://acme.test/careers",
        }),
      ),
    ).toBe(true);
  });

  it("rejects a page with only one or two job links", () => {
    // One matched link is almost always a nav item, not a board.
    expect(acceptsAsVerifiedSource(verification({ postingsSeen: 1 }))).toBe(false);
    expect(acceptsAsVerifiedSource(verification({ postingsSeen: 2 }))).toBe(false);
  });

  it("rejects a page that redirected away from anything careers-shaped", () => {
    // Real case: siemens.com/careers 302s to /company/about, which still has
    // plenty of links and would otherwise pass on link count alone.
    expect(
      acceptsAsVerifiedSource(
        verification({
          postingsSeen: 20,
          finalUrl: "https://www.siemens.com/en-gb/company/about/",
        }),
      ),
    ).toBe(false);
  });

  it("judges the URL it LANDED on, not the one registered", () => {
    expect(
      acceptsAsVerifiedSource(
        verification({
          url: "https://acme.test/about",
          finalUrl: "https://acme.test/careers",
          postingsSeen: 9,
        }),
      ),
    ).toBe(true);
  });
});

describe("acceptsAsVerifiedSource — health gates", () => {
  it.each(["BLOCKED", "BROKEN", "UNAVAILABLE", "UNKNOWN"] as const)("rejects %s", (health) => {
    expect(acceptsAsVerifiedSource(verification({ health, postingsSeen: 50 }))).toBe(false);
  });

  it("accepts REDIRECTED — a moved source is still a working source", () => {
    expect(
      acceptsAsVerifiedSource(
        verification({ health: "REDIRECTED", detectedPlatform: "greenhouse", postingsSeen: 3 }),
      ),
    ).toBe(true);
  });

  it("rejects a verdict with no detected platform", () => {
    expect(acceptsAsVerifiedSource(verification({ detectedPlatform: null }))).toBe(false);
  });
});

describe("effectiveHealth — stored status matches crawlability", () => {
  it("keeps a genuinely verified source as-is", () => {
    const result = effectiveHealth(
      verification({ detectedPlatform: "greenhouse", postingsSeen: 12 }),
    );
    expect(result.health).toBe("HEALTHY");
    expect(result.detectedPlatform).toBe("greenhouse");
  });

  it("downgrades a HEALTHY page that failed acceptance to UNKNOWN", () => {
    // Otherwise the registry ends up with rows that read "HEALTHY" while being
    // disabled, and an operator cannot tell why they are not running.
    const result = effectiveHealth(verification({ postingsSeen: 1 }));
    expect(result.health).toBe("UNKNOWN");
    expect(result.detectedPlatform).toBeNull();
    expect(result.errorReason).toMatch(/no jobs board confirmed/i);
  });

  it("downgrades an empty ATS board discovered by a guessed slug", () => {
    const result = effectiveHealth(
      verification({ detectedPlatform: "smartrecruiters", postingsSeen: 0 }),
    );
    expect(result.health).toBe("UNKNOWN");
    expect(result.detectedPlatform).toBeNull();
  });

  it.each(["BLOCKED", "BROKEN", "UNAVAILABLE"] as const)(
    "keeps %s and its reason — those are actionable facts",
    (health) => {
      const result = effectiveHealth(
        verification({ health, detectedPlatform: "greenhouse", errorReason: "HTTP 403" }),
      );
      expect(result.health).toBe(health);
      expect(result.errorReason).toBe("HTTP 403");
    },
  );

  it("guarantees the invariant: a positive stored health is always crawlable", () => {
    const cases = [
      verification({ postingsSeen: 1 }),
      verification({ detectedPlatform: "lever", postingsSeen: 0 }),
      verification({ postingsSeen: 30, finalUrl: "https://acme.test/company/about" }),
      verification({ detectedPlatform: "ashby", postingsSeen: 4 }),
      verification({ health: "BROKEN" }),
    ];
    for (const candidate of cases) {
      const stored = effectiveHealth(candidate);
      const positive = stored.health === "HEALTHY" || stored.health === "REDIRECTED";
      expect(positive).toBe(acceptsAsVerifiedSource(candidate));
    }
  });
});
