import { createFileRoute } from "@tanstack/react-router";
import { LegalDocument, LegalSection } from "@/components/site/LegalDocument";
import { CONTACT_EMAIL } from "@/content/extension";
import { pageSeo } from "@/content/site";

export const Route = createFileRoute("/terms")({
  head: () => ({
    ...pageSeo({
      path: "/terms",
      title: "Terms of Service — OfferLyst",
      description: "The terms for using OfferLyst, currently free during early access.",
    }),
  }),
  component: TermsPage,
});

const LAST_UPDATED = "August 20, 2026";

function TermsPage() {
  return (
    <LegalDocument
      title="Terms of Service"
      lastUpdated={LAST_UPDATED}
      intro={
        <>
          These terms cover using OfferLyst while it's free and in early access. There is no paid
          tier today, so nothing here covers payment, refunds, or subscriptions — those terms will
          be written if and when a paid plan launches.
        </>
      }
    >
      <LegalSection title="Using the service">
        <p>
          OfferLyst is a workspace for tracking your job search: saving jobs, tracking
          applications, and AI-assisted resume, cover letter and interview preparation tools. You
          need an account to use it. You're responsible for the accuracy of the information you
          provide and for keeping your account credentials secure.
        </p>
      </LegalSection>

      <LegalSection title="Eligibility" needsReview>
        <p>
          You must be able to enter into a binding agreement to use OfferLyst. The specific
          minimum age and any jurisdiction-specific requirements should be confirmed with a lawyer
          before launch.
        </p>
      </LegalSection>

      <LegalSection title="Acceptable use">
        <p>You agree not to:</p>
        <ul>
          <li>Use the service to violate any law or another person's rights</li>
          <li>Attempt to bypass rate limits, credit limits, or access controls</li>
          <li>Scrape, resell, or redistribute data from the service</li>
          <li>Use the Chrome extension in a way that violates the terms of the job sites it runs on</li>
        </ul>
      </LegalSection>

      <LegalSection title="AI-generated content">
        <p>
          Resume match scores, ATS reports, resume suggestions, cover letter drafts and interview
          preparation content are generated by AI and are meant to assist, not replace, your own
          judgment. AI output can be inaccurate or miss context an AI system doesn't have. Review
          anything AI-generated before relying on it — sending a cover letter, changing your
          resume, or walking into an interview based on it is your decision, and you're
          responsible for the result.
        </p>
      </LegalSection>

      <LegalSection title="Your content">
        <p>
          You own the resumes, notes, and other content you upload or create in OfferLyst. You
          grant us the limited right to store and process that content solely to provide the
          service to you (including sending it to the AI providers described in the Privacy
          Policy when you trigger an AI feature). We don't claim ownership of your content and
          don't use it for anything beyond operating the product for you.
        </p>
      </LegalSection>

      <LegalSection title="Free access, no current payment terms">
        <p>
          OfferLyst does not charge for access today. Every account gets a free allowance of AI
          credits; core tracking features (saving jobs, application tracking, notes, analytics)
          are not credit-limited. We may introduce paid plans in the future; if we do, these terms
          will be updated first and nothing will change for existing usage without notice.
        </p>
      </LegalSection>

      <LegalSection title="Service availability">
        <p>
          OfferLyst is an early-access product provided "as is," without a guarantee of uptime or
          that any specific feature will remain available in its current form. We aim to keep the
          service reliable but don't promise it will be error-free or uninterrupted.
        </p>
      </LegalSection>

      <LegalSection title="Termination">
        <p>
          You may stop using OfferLyst at any time. We may suspend or terminate access for
          accounts that violate these terms. There is currently no automated self-service account
          deletion — see the Privacy Policy's Data retention section for how to request full
          account deletion today.
        </p>
      </LegalSection>

      <LegalSection title="Limitation of liability" needsReview>
        <p>
          OfferLyst is provided without warranties of any kind, express or implied. To the maximum
          extent permitted by law, we are not liable for indirect, incidental, or consequential
          damages arising from your use of the service, including decisions made based on
          AI-generated content. This section is a placeholder reflecting common practice for an
          early-access product and has not been drafted or reviewed by a lawyer — it should be
          before this product is relied on commercially.
        </p>
      </LegalSection>

      <LegalSection title="Governing law" needsReview>
        <p>
          A specific governing law and dispute-resolution jurisdiction have not been chosen yet.
          This should be decided with legal input based on where the business is incorporated and
          where its users are located, then stated explicitly here.
        </p>
      </LegalSection>

      <LegalSection title="Changes to these terms">
        <p>
          If these terms change materially, we'll update this page and change the "Last updated"
          date above.
        </p>
      </LegalSection>

      <LegalSection title="Contact">
        <p>
          Questions about these terms can be sent to{" "}
          <a href={`mailto:${CONTACT_EMAIL}`} className="text-[#93C5FD] hover:underline">
            {CONTACT_EMAIL}
          </a>
          .
        </p>
      </LegalSection>
    </LegalDocument>
  );
}
