/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupabaseStatusRouteImport } from './routes/supabase-status'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExtensionRouteImport } from './routes/extension'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSavedRouteImport } from './routes/dashboard.saved'
import { Route as DashboardResumesRouteImport } from './routes/dashboard.resumes'
import { Route as DashboardNotesRouteImport } from './routes/dashboard.notes'
import { Route as DashboardJobsRouteImport } from './routes/dashboard.jobs'
import { Route as DashboardInterviewsRouteImport } from './routes/dashboard.interviews'
import { Route as DashboardInboxRouteImport } from './routes/dashboard.inbox'
import { Route as DashboardCoverLettersRouteImport } from './routes/dashboard.cover-letters'
import { Route as DashboardCollectionsRouteImport } from './routes/dashboard.collections'
import { Route as DashboardApplicationsRouteImport } from './routes/dashboard.applications'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardJobsIndexRouteImport } from './routes/dashboard.jobs.index'
import { Route as DashboardInterviewsIndexRouteImport } from './routes/dashboard.interviews.index'
import { Route as DashboardCoverLettersIndexRouteImport } from './routes/dashboard.cover-letters.index'
import { Route as DashboardCollectionsIndexRouteImport } from './routes/dashboard.collections.index'
import { Route as DashboardApplicationsIndexRouteImport } from './routes/dashboard.applications.index'
import { Route as DashboardJobsJobIdRouteImport } from './routes/dashboard.jobs.$jobId'
import { Route as DashboardInterviewsInterviewIdRouteImport } from './routes/dashboard.interviews.$interviewId'
import { Route as DashboardCoverLettersCoverLetterIdRouteImport } from './routes/dashboard.cover-letters.$coverLetterId'
import { Route as DashboardCollectionsCollectionIdRouteImport } from './routes/dashboard.collections.$collectionId'
import { Route as DashboardApplicationsApplicationIdRouteImport } from './routes/dashboard.applications.$applicationId'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google.callback'
import { Route as DashboardInterviewsInterviewIdIndexRouteImport } from './routes/dashboard.interviews.$interviewId.index'
import { Route as DashboardResumesResumeIdOptimizeRouteImport } from './routes/dashboard.resumes_.$resumeId.optimize'
import { Route as DashboardInterviewsInterviewIdPrepRouteImport } from './routes/dashboard.interviews.$interviewId.prep'
import { Route as DashboardInterviewsInterviewIdMockRouteImport } from './routes/dashboard.interviews.$interviewId.mock'
import { Route as DashboardInterviewsInterviewIdMockIndexRouteImport } from './routes/dashboard.interviews.$interviewId.mock.index'
import { Route as DashboardInterviewsInterviewIdMockSessionIdRouteImport } from './routes/dashboard_.interviews.$interviewId.mock.$sessionId'
import { Route as DashboardInterviewsInterviewIdMockSessionIdReportRouteImport } from './routes/dashboard.interviews.$interviewId.mock.$sessionId.report'

const SupabaseStatusRoute = SupabaseStatusRouteImport.update({
  id: '/supabase-status',
  path: '/supabase-status',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionRoute = ExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSavedRoute = DashboardSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResumesRoute = DashboardResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotesRoute = DashboardNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInterviewsRoute = DashboardInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInboxRoute = DashboardInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoverLettersRoute = DashboardCoverLettersRouteImport.update({
  id: '/cover-letters',
  path: '/cover-letters',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCollectionsRoute = DashboardCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApplicationsRoute = DashboardApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsIndexRoute = DashboardJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardJobsRoute,
} as any)
const DashboardInterviewsIndexRoute =
  DashboardInterviewsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardInterviewsRoute,
  } as any)
const DashboardCoverLettersIndexRoute =
  DashboardCoverLettersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardCoverLettersRoute,
  } as any)
const DashboardCollectionsIndexRoute =
  DashboardCollectionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardCollectionsRoute,
  } as any)
const DashboardApplicationsIndexRoute =
  DashboardApplicationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardApplicationsRoute,
  } as any)
const DashboardJobsJobIdRoute = DashboardJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => DashboardJobsRoute,
} as any)
const DashboardInterviewsInterviewIdRoute =
  DashboardInterviewsInterviewIdRouteImport.update({
    id: '/$interviewId',
    path: '/$interviewId',
    getParentRoute: () => DashboardInterviewsRoute,
  } as any)
const DashboardCoverLettersCoverLetterIdRoute =
  DashboardCoverLettersCoverLetterIdRouteImport.update({
    id: '/$coverLetterId',
    path: '/$coverLetterId',
    getParentRoute: () => DashboardCoverLettersRoute,
  } as any)
const DashboardCollectionsCollectionIdRoute =
  DashboardCollectionsCollectionIdRouteImport.update({
    id: '/$collectionId',
    path: '/$collectionId',
    getParentRoute: () => DashboardCollectionsRoute,
  } as any)
const DashboardApplicationsApplicationIdRoute =
  DashboardApplicationsApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => DashboardApplicationsRoute,
  } as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInterviewsInterviewIdIndexRoute =
  DashboardInterviewsInterviewIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardInterviewsInterviewIdRoute,
  } as any)
const DashboardResumesResumeIdOptimizeRoute =
  DashboardResumesResumeIdOptimizeRouteImport.update({
    id: '/resumes_/$resumeId/optimize',
    path: '/resumes/$resumeId/optimize',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardInterviewsInterviewIdPrepRoute =
  DashboardInterviewsInterviewIdPrepRouteImport.update({
    id: '/prep',
    path: '/prep',
    getParentRoute: () => DashboardInterviewsInterviewIdRoute,
  } as any)
const DashboardInterviewsInterviewIdMockRoute =
  DashboardInterviewsInterviewIdMockRouteImport.update({
    id: '/mock',
    path: '/mock',
    getParentRoute: () => DashboardInterviewsInterviewIdRoute,
  } as any)
const DashboardInterviewsInterviewIdMockIndexRoute =
  DashboardInterviewsInterviewIdMockIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardInterviewsInterviewIdMockRoute,
  } as any)
const DashboardInterviewsInterviewIdMockSessionIdRoute =
  DashboardInterviewsInterviewIdMockSessionIdRouteImport.update({
    id: '/dashboard_/interviews/$interviewId/mock/$sessionId',
    path: '/dashboard/interviews/$interviewId/mock/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardInterviewsInterviewIdMockSessionIdReportRoute =
  DashboardInterviewsInterviewIdMockSessionIdReportRouteImport.update({
    id: '/$sessionId/report',
    path: '/$sessionId/report',
    getParentRoute: () => DashboardInterviewsInterviewIdMockRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/extension': typeof ExtensionRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supabase-status': typeof SupabaseStatusRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/applications': typeof DashboardApplicationsRouteWithChildren
  '/dashboard/collections': typeof DashboardCollectionsRouteWithChildren
  '/dashboard/cover-letters': typeof DashboardCoverLettersRouteWithChildren
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/interviews': typeof DashboardInterviewsRouteWithChildren
  '/dashboard/jobs': typeof DashboardJobsRouteWithChildren
  '/dashboard/notes': typeof DashboardNotesRoute
  '/dashboard/resumes': typeof DashboardResumesRoute
  '/dashboard/saved': typeof DashboardSavedRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/dashboard/applications/$applicationId': typeof DashboardApplicationsApplicationIdRoute
  '/dashboard/collections/$collectionId': typeof DashboardCollectionsCollectionIdRoute
  '/dashboard/cover-letters/$coverLetterId': typeof DashboardCoverLettersCoverLetterIdRoute
  '/dashboard/interviews/$interviewId': typeof DashboardInterviewsInterviewIdRouteWithChildren
  '/dashboard/jobs/$jobId': typeof DashboardJobsJobIdRoute
  '/dashboard/applications/': typeof DashboardApplicationsIndexRoute
  '/dashboard/collections/': typeof DashboardCollectionsIndexRoute
  '/dashboard/cover-letters/': typeof DashboardCoverLettersIndexRoute
  '/dashboard/interviews/': typeof DashboardInterviewsIndexRoute
  '/dashboard/jobs/': typeof DashboardJobsIndexRoute
  '/dashboard/interviews/$interviewId/mock': typeof DashboardInterviewsInterviewIdMockRouteWithChildren
  '/dashboard/interviews/$interviewId/prep': typeof DashboardInterviewsInterviewIdPrepRoute
  '/dashboard/resumes/$resumeId/optimize': typeof DashboardResumesResumeIdOptimizeRoute
  '/dashboard/interviews/$interviewId/': typeof DashboardInterviewsInterviewIdIndexRoute
  '/dashboard/interviews/$interviewId/mock/$sessionId': typeof DashboardInterviewsInterviewIdMockSessionIdRoute
  '/dashboard/interviews/$interviewId/mock/': typeof DashboardInterviewsInterviewIdMockIndexRoute
  '/dashboard/interviews/$interviewId/mock/$sessionId/report': typeof DashboardInterviewsInterviewIdMockSessionIdReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/extension': typeof ExtensionRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supabase-status': typeof SupabaseStatusRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/notes': typeof DashboardNotesRoute
  '/dashboard/resumes': typeof DashboardResumesRoute
  '/dashboard/saved': typeof DashboardSavedRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/dashboard/applications/$applicationId': typeof DashboardApplicationsApplicationIdRoute
  '/dashboard/collections/$collectionId': typeof DashboardCollectionsCollectionIdRoute
  '/dashboard/cover-letters/$coverLetterId': typeof DashboardCoverLettersCoverLetterIdRoute
  '/dashboard/jobs/$jobId': typeof DashboardJobsJobIdRoute
  '/dashboard/applications': typeof DashboardApplicationsIndexRoute
  '/dashboard/collections': typeof DashboardCollectionsIndexRoute
  '/dashboard/cover-letters': typeof DashboardCoverLettersIndexRoute
  '/dashboard/interviews': typeof DashboardInterviewsIndexRoute
  '/dashboard/jobs': typeof DashboardJobsIndexRoute
  '/dashboard/interviews/$interviewId/prep': typeof DashboardInterviewsInterviewIdPrepRoute
  '/dashboard/resumes/$resumeId/optimize': typeof DashboardResumesResumeIdOptimizeRoute
  '/dashboard/interviews/$interviewId': typeof DashboardInterviewsInterviewIdIndexRoute
  '/dashboard/interviews/$interviewId/mock/$sessionId': typeof DashboardInterviewsInterviewIdMockSessionIdRoute
  '/dashboard/interviews/$interviewId/mock': typeof DashboardInterviewsInterviewIdMockIndexRoute
  '/dashboard/interviews/$interviewId/mock/$sessionId/report': typeof DashboardInterviewsInterviewIdMockSessionIdReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/extension': typeof ExtensionRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supabase-status': typeof SupabaseStatusRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/applications': typeof DashboardApplicationsRouteWithChildren
  '/dashboard/collections': typeof DashboardCollectionsRouteWithChildren
  '/dashboard/cover-letters': typeof DashboardCoverLettersRouteWithChildren
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/interviews': typeof DashboardInterviewsRouteWithChildren
  '/dashboard/jobs': typeof DashboardJobsRouteWithChildren
  '/dashboard/notes': typeof DashboardNotesRoute
  '/dashboard/resumes': typeof DashboardResumesRoute
  '/dashboard/saved': typeof DashboardSavedRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/dashboard/applications/$applicationId': typeof DashboardApplicationsApplicationIdRoute
  '/dashboard/collections/$collectionId': typeof DashboardCollectionsCollectionIdRoute
  '/dashboard/cover-letters/$coverLetterId': typeof DashboardCoverLettersCoverLetterIdRoute
  '/dashboard/interviews/$interviewId': typeof DashboardInterviewsInterviewIdRouteWithChildren
  '/dashboard/jobs/$jobId': typeof DashboardJobsJobIdRoute
  '/dashboard/applications/': typeof DashboardApplicationsIndexRoute
  '/dashboard/collections/': typeof DashboardCollectionsIndexRoute
  '/dashboard/cover-letters/': typeof DashboardCoverLettersIndexRoute
  '/dashboard/interviews/': typeof DashboardInterviewsIndexRoute
  '/dashboard/jobs/': typeof DashboardJobsIndexRoute
  '/dashboard/interviews/$interviewId/mock': typeof DashboardInterviewsInterviewIdMockRouteWithChildren
  '/dashboard/interviews/$interviewId/prep': typeof DashboardInterviewsInterviewIdPrepRoute
  '/dashboard/resumes_/$resumeId/optimize': typeof DashboardResumesResumeIdOptimizeRoute
  '/dashboard/interviews/$interviewId/': typeof DashboardInterviewsInterviewIdIndexRoute
  '/dashboard_/interviews/$interviewId/mock/$sessionId': typeof DashboardInterviewsInterviewIdMockSessionIdRoute
  '/dashboard/interviews/$interviewId/mock/': typeof DashboardInterviewsInterviewIdMockIndexRoute
  '/dashboard/interviews/$interviewId/mock/$sessionId/report': typeof DashboardInterviewsInterviewIdMockSessionIdReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/extension'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/supabase-status'
    | '/dashboard/analytics'
    | '/dashboard/applications'
    | '/dashboard/collections'
    | '/dashboard/cover-letters'
    | '/dashboard/inbox'
    | '/dashboard/interviews'
    | '/dashboard/jobs'
    | '/dashboard/notes'
    | '/dashboard/resumes'
    | '/dashboard/saved'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/auth/google/callback'
    | '/dashboard/applications/$applicationId'
    | '/dashboard/collections/$collectionId'
    | '/dashboard/cover-letters/$coverLetterId'
    | '/dashboard/interviews/$interviewId'
    | '/dashboard/jobs/$jobId'
    | '/dashboard/applications/'
    | '/dashboard/collections/'
    | '/dashboard/cover-letters/'
    | '/dashboard/interviews/'
    | '/dashboard/jobs/'
    | '/dashboard/interviews/$interviewId/mock'
    | '/dashboard/interviews/$interviewId/prep'
    | '/dashboard/resumes/$resumeId/optimize'
    | '/dashboard/interviews/$interviewId/'
    | '/dashboard/interviews/$interviewId/mock/$sessionId'
    | '/dashboard/interviews/$interviewId/mock/'
    | '/dashboard/interviews/$interviewId/mock/$sessionId/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/extension'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/supabase-status'
    | '/dashboard/analytics'
    | '/dashboard/inbox'
    | '/dashboard/notes'
    | '/dashboard/resumes'
    | '/dashboard/saved'
    | '/dashboard/settings'
    | '/dashboard'
    | '/auth/google/callback'
    | '/dashboard/applications/$applicationId'
    | '/dashboard/collections/$collectionId'
    | '/dashboard/cover-letters/$coverLetterId'
    | '/dashboard/jobs/$jobId'
    | '/dashboard/applications'
    | '/dashboard/collections'
    | '/dashboard/cover-letters'
    | '/dashboard/interviews'
    | '/dashboard/jobs'
    | '/dashboard/interviews/$interviewId/prep'
    | '/dashboard/resumes/$resumeId/optimize'
    | '/dashboard/interviews/$interviewId'
    | '/dashboard/interviews/$interviewId/mock/$sessionId'
    | '/dashboard/interviews/$interviewId/mock'
    | '/dashboard/interviews/$interviewId/mock/$sessionId/report'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/extension'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/supabase-status'
    | '/dashboard/analytics'
    | '/dashboard/applications'
    | '/dashboard/collections'
    | '/dashboard/cover-letters'
    | '/dashboard/inbox'
    | '/dashboard/interviews'
    | '/dashboard/jobs'
    | '/dashboard/notes'
    | '/dashboard/resumes'
    | '/dashboard/saved'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/auth/google/callback'
    | '/dashboard/applications/$applicationId'
    | '/dashboard/collections/$collectionId'
    | '/dashboard/cover-letters/$coverLetterId'
    | '/dashboard/interviews/$interviewId'
    | '/dashboard/jobs/$jobId'
    | '/dashboard/applications/'
    | '/dashboard/collections/'
    | '/dashboard/cover-letters/'
    | '/dashboard/interviews/'
    | '/dashboard/jobs/'
    | '/dashboard/interviews/$interviewId/mock'
    | '/dashboard/interviews/$interviewId/prep'
    | '/dashboard/resumes_/$resumeId/optimize'
    | '/dashboard/interviews/$interviewId/'
    | '/dashboard_/interviews/$interviewId/mock/$sessionId'
    | '/dashboard/interviews/$interviewId/mock/'
    | '/dashboard/interviews/$interviewId/mock/$sessionId/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ExtensionRoute: typeof ExtensionRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupabaseStatusRoute: typeof SupabaseStatusRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  DashboardInterviewsInterviewIdMockSessionIdRoute: typeof DashboardInterviewsInterviewIdMockSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supabase-status': {
      id: '/supabase-status'
      path: '/supabase-status'
      fullPath: '/supabase-status'
      preLoaderRoute: typeof SupabaseStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension': {
      id: '/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof ExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/saved': {
      id: '/dashboard/saved'
      path: '/saved'
      fullPath: '/dashboard/saved'
      preLoaderRoute: typeof DashboardSavedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resumes': {
      id: '/dashboard/resumes'
      path: '/resumes'
      fullPath: '/dashboard/resumes'
      preLoaderRoute: typeof DashboardResumesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notes': {
      id: '/dashboard/notes'
      path: '/notes'
      fullPath: '/dashboard/notes'
      preLoaderRoute: typeof DashboardNotesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/interviews': {
      id: '/dashboard/interviews'
      path: '/interviews'
      fullPath: '/dashboard/interviews'
      preLoaderRoute: typeof DashboardInterviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inbox': {
      id: '/dashboard/inbox'
      path: '/inbox'
      fullPath: '/dashboard/inbox'
      preLoaderRoute: typeof DashboardInboxRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cover-letters': {
      id: '/dashboard/cover-letters'
      path: '/cover-letters'
      fullPath: '/dashboard/cover-letters'
      preLoaderRoute: typeof DashboardCoverLettersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/collections': {
      id: '/dashboard/collections'
      path: '/collections'
      fullPath: '/dashboard/collections'
      preLoaderRoute: typeof DashboardCollectionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/applications': {
      id: '/dashboard/applications'
      path: '/applications'
      fullPath: '/dashboard/applications'
      preLoaderRoute: typeof DashboardApplicationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jobs/': {
      id: '/dashboard/jobs/'
      path: '/'
      fullPath: '/dashboard/jobs/'
      preLoaderRoute: typeof DashboardJobsIndexRouteImport
      parentRoute: typeof DashboardJobsRoute
    }
    '/dashboard/interviews/': {
      id: '/dashboard/interviews/'
      path: '/'
      fullPath: '/dashboard/interviews/'
      preLoaderRoute: typeof DashboardInterviewsIndexRouteImport
      parentRoute: typeof DashboardInterviewsRoute
    }
    '/dashboard/cover-letters/': {
      id: '/dashboard/cover-letters/'
      path: '/'
      fullPath: '/dashboard/cover-letters/'
      preLoaderRoute: typeof DashboardCoverLettersIndexRouteImport
      parentRoute: typeof DashboardCoverLettersRoute
    }
    '/dashboard/collections/': {
      id: '/dashboard/collections/'
      path: '/'
      fullPath: '/dashboard/collections/'
      preLoaderRoute: typeof DashboardCollectionsIndexRouteImport
      parentRoute: typeof DashboardCollectionsRoute
    }
    '/dashboard/applications/': {
      id: '/dashboard/applications/'
      path: '/'
      fullPath: '/dashboard/applications/'
      preLoaderRoute: typeof DashboardApplicationsIndexRouteImport
      parentRoute: typeof DashboardApplicationsRoute
    }
    '/dashboard/jobs/$jobId': {
      id: '/dashboard/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/dashboard/jobs/$jobId'
      preLoaderRoute: typeof DashboardJobsJobIdRouteImport
      parentRoute: typeof DashboardJobsRoute
    }
    '/dashboard/interviews/$interviewId': {
      id: '/dashboard/interviews/$interviewId'
      path: '/$interviewId'
      fullPath: '/dashboard/interviews/$interviewId'
      preLoaderRoute: typeof DashboardInterviewsInterviewIdRouteImport
      parentRoute: typeof DashboardInterviewsRoute
    }
    '/dashboard/cover-letters/$coverLetterId': {
      id: '/dashboard/cover-letters/$coverLetterId'
      path: '/$coverLetterId'
      fullPath: '/dashboard/cover-letters/$coverLetterId'
      preLoaderRoute: typeof DashboardCoverLettersCoverLetterIdRouteImport
      parentRoute: typeof DashboardCoverLettersRoute
    }
    '/dashboard/collections/$collectionId': {
      id: '/dashboard/collections/$collectionId'
      path: '/$collectionId'
      fullPath: '/dashboard/collections/$collectionId'
      preLoaderRoute: typeof DashboardCollectionsCollectionIdRouteImport
      parentRoute: typeof DashboardCollectionsRoute
    }
    '/dashboard/applications/$applicationId': {
      id: '/dashboard/applications/$applicationId'
      path: '/$applicationId'
      fullPath: '/dashboard/applications/$applicationId'
      preLoaderRoute: typeof DashboardApplicationsApplicationIdRouteImport
      parentRoute: typeof DashboardApplicationsRoute
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/interviews/$interviewId/': {
      id: '/dashboard/interviews/$interviewId/'
      path: '/'
      fullPath: '/dashboard/interviews/$interviewId/'
      preLoaderRoute: typeof DashboardInterviewsInterviewIdIndexRouteImport
      parentRoute: typeof DashboardInterviewsInterviewIdRoute
    }
    '/dashboard/resumes_/$resumeId/optimize': {
      id: '/dashboard/resumes_/$resumeId/optimize'
      path: '/resumes/$resumeId/optimize'
      fullPath: '/dashboard/resumes/$resumeId/optimize'
      preLoaderRoute: typeof DashboardResumesResumeIdOptimizeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/interviews/$interviewId/prep': {
      id: '/dashboard/interviews/$interviewId/prep'
      path: '/prep'
      fullPath: '/dashboard/interviews/$interviewId/prep'
      preLoaderRoute: typeof DashboardInterviewsInterviewIdPrepRouteImport
      parentRoute: typeof DashboardInterviewsInterviewIdRoute
    }
    '/dashboard/interviews/$interviewId/mock': {
      id: '/dashboard/interviews/$interviewId/mock'
      path: '/mock'
      fullPath: '/dashboard/interviews/$interviewId/mock'
      preLoaderRoute: typeof DashboardInterviewsInterviewIdMockRouteImport
      parentRoute: typeof DashboardInterviewsInterviewIdRoute
    }
    '/dashboard/interviews/$interviewId/mock/': {
      id: '/dashboard/interviews/$interviewId/mock/'
      path: '/'
      fullPath: '/dashboard/interviews/$interviewId/mock/'
      preLoaderRoute: typeof DashboardInterviewsInterviewIdMockIndexRouteImport
      parentRoute: typeof DashboardInterviewsInterviewIdMockRoute
    }
    '/dashboard_/interviews/$interviewId/mock/$sessionId': {
      id: '/dashboard_/interviews/$interviewId/mock/$sessionId'
      path: '/dashboard/interviews/$interviewId/mock/$sessionId'
      fullPath: '/dashboard/interviews/$interviewId/mock/$sessionId'
      preLoaderRoute: typeof DashboardInterviewsInterviewIdMockSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/interviews/$interviewId/mock/$sessionId/report': {
      id: '/dashboard/interviews/$interviewId/mock/$sessionId/report'
      path: '/$sessionId/report'
      fullPath: '/dashboard/interviews/$interviewId/mock/$sessionId/report'
      preLoaderRoute: typeof DashboardInterviewsInterviewIdMockSessionIdReportRouteImport
      parentRoute: typeof DashboardInterviewsInterviewIdMockRoute
    }
  }
}

interface DashboardApplicationsRouteChildren {
  DashboardApplicationsApplicationIdRoute: typeof DashboardApplicationsApplicationIdRoute
  DashboardApplicationsIndexRoute: typeof DashboardApplicationsIndexRoute
}

const DashboardApplicationsRouteChildren: DashboardApplicationsRouteChildren = {
  DashboardApplicationsApplicationIdRoute:
    DashboardApplicationsApplicationIdRoute,
  DashboardApplicationsIndexRoute: DashboardApplicationsIndexRoute,
}

const DashboardApplicationsRouteWithChildren =
  DashboardApplicationsRoute._addFileChildren(
    DashboardApplicationsRouteChildren,
  )

interface DashboardCollectionsRouteChildren {
  DashboardCollectionsCollectionIdRoute: typeof DashboardCollectionsCollectionIdRoute
  DashboardCollectionsIndexRoute: typeof DashboardCollectionsIndexRoute
}

const DashboardCollectionsRouteChildren: DashboardCollectionsRouteChildren = {
  DashboardCollectionsCollectionIdRoute: DashboardCollectionsCollectionIdRoute,
  DashboardCollectionsIndexRoute: DashboardCollectionsIndexRoute,
}

const DashboardCollectionsRouteWithChildren =
  DashboardCollectionsRoute._addFileChildren(DashboardCollectionsRouteChildren)

interface DashboardCoverLettersRouteChildren {
  DashboardCoverLettersCoverLetterIdRoute: typeof DashboardCoverLettersCoverLetterIdRoute
  DashboardCoverLettersIndexRoute: typeof DashboardCoverLettersIndexRoute
}

const DashboardCoverLettersRouteChildren: DashboardCoverLettersRouteChildren = {
  DashboardCoverLettersCoverLetterIdRoute:
    DashboardCoverLettersCoverLetterIdRoute,
  DashboardCoverLettersIndexRoute: DashboardCoverLettersIndexRoute,
}

const DashboardCoverLettersRouteWithChildren =
  DashboardCoverLettersRoute._addFileChildren(
    DashboardCoverLettersRouteChildren,
  )

interface DashboardInterviewsInterviewIdMockRouteChildren {
  DashboardInterviewsInterviewIdMockIndexRoute: typeof DashboardInterviewsInterviewIdMockIndexRoute
  DashboardInterviewsInterviewIdMockSessionIdReportRoute: typeof DashboardInterviewsInterviewIdMockSessionIdReportRoute
}

const DashboardInterviewsInterviewIdMockRouteChildren: DashboardInterviewsInterviewIdMockRouteChildren =
  {
    DashboardInterviewsInterviewIdMockIndexRoute:
      DashboardInterviewsInterviewIdMockIndexRoute,
    DashboardInterviewsInterviewIdMockSessionIdReportRoute:
      DashboardInterviewsInterviewIdMockSessionIdReportRoute,
  }

const DashboardInterviewsInterviewIdMockRouteWithChildren =
  DashboardInterviewsInterviewIdMockRoute._addFileChildren(
    DashboardInterviewsInterviewIdMockRouteChildren,
  )

interface DashboardInterviewsInterviewIdRouteChildren {
  DashboardInterviewsInterviewIdMockRoute: typeof DashboardInterviewsInterviewIdMockRouteWithChildren
  DashboardInterviewsInterviewIdPrepRoute: typeof DashboardInterviewsInterviewIdPrepRoute
  DashboardInterviewsInterviewIdIndexRoute: typeof DashboardInterviewsInterviewIdIndexRoute
}

const DashboardInterviewsInterviewIdRouteChildren: DashboardInterviewsInterviewIdRouteChildren =
  {
    DashboardInterviewsInterviewIdMockRoute:
      DashboardInterviewsInterviewIdMockRouteWithChildren,
    DashboardInterviewsInterviewIdPrepRoute:
      DashboardInterviewsInterviewIdPrepRoute,
    DashboardInterviewsInterviewIdIndexRoute:
      DashboardInterviewsInterviewIdIndexRoute,
  }

const DashboardInterviewsInterviewIdRouteWithChildren =
  DashboardInterviewsInterviewIdRoute._addFileChildren(
    DashboardInterviewsInterviewIdRouteChildren,
  )

interface DashboardInterviewsRouteChildren {
  DashboardInterviewsInterviewIdRoute: typeof DashboardInterviewsInterviewIdRouteWithChildren
  DashboardInterviewsIndexRoute: typeof DashboardInterviewsIndexRoute
}

const DashboardInterviewsRouteChildren: DashboardInterviewsRouteChildren = {
  DashboardInterviewsInterviewIdRoute:
    DashboardInterviewsInterviewIdRouteWithChildren,
  DashboardInterviewsIndexRoute: DashboardInterviewsIndexRoute,
}

const DashboardInterviewsRouteWithChildren =
  DashboardInterviewsRoute._addFileChildren(DashboardInterviewsRouteChildren)

interface DashboardJobsRouteChildren {
  DashboardJobsJobIdRoute: typeof DashboardJobsJobIdRoute
  DashboardJobsIndexRoute: typeof DashboardJobsIndexRoute
}

const DashboardJobsRouteChildren: DashboardJobsRouteChildren = {
  DashboardJobsJobIdRoute: DashboardJobsJobIdRoute,
  DashboardJobsIndexRoute: DashboardJobsIndexRoute,
}

const DashboardJobsRouteWithChildren = DashboardJobsRoute._addFileChildren(
  DashboardJobsRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardApplicationsRoute: typeof DashboardApplicationsRouteWithChildren
  DashboardCollectionsRoute: typeof DashboardCollectionsRouteWithChildren
  DashboardCoverLettersRoute: typeof DashboardCoverLettersRouteWithChildren
  DashboardInboxRoute: typeof DashboardInboxRoute
  DashboardInterviewsRoute: typeof DashboardInterviewsRouteWithChildren
  DashboardJobsRoute: typeof DashboardJobsRouteWithChildren
  DashboardNotesRoute: typeof DashboardNotesRoute
  DashboardResumesRoute: typeof DashboardResumesRoute
  DashboardSavedRoute: typeof DashboardSavedRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardResumesResumeIdOptimizeRoute: typeof DashboardResumesResumeIdOptimizeRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardApplicationsRoute: DashboardApplicationsRouteWithChildren,
  DashboardCollectionsRoute: DashboardCollectionsRouteWithChildren,
  DashboardCoverLettersRoute: DashboardCoverLettersRouteWithChildren,
  DashboardInboxRoute: DashboardInboxRoute,
  DashboardInterviewsRoute: DashboardInterviewsRouteWithChildren,
  DashboardJobsRoute: DashboardJobsRouteWithChildren,
  DashboardNotesRoute: DashboardNotesRoute,
  DashboardResumesRoute: DashboardResumesRoute,
  DashboardSavedRoute: DashboardSavedRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardResumesResumeIdOptimizeRoute: DashboardResumesResumeIdOptimizeRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ExtensionRoute: ExtensionRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupabaseStatusRoute: SupabaseStatusRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  DashboardInterviewsInterviewIdMockSessionIdRoute:
    DashboardInterviewsInterviewIdMockSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
